# portainer/portainer-ce
version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: con-portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    ports:
      - "9000:9000"
      - "9443:9443"
    networks:
      - portainer-net

networks:
  portainer-net: